### PR TITLE
Checkout Finland

### PR DESCRIPTION
**Pull request by tuomasb**
Checkout Finland integration with unit tests and remote tests. Would love to get this merged. Any comments/feedback?

### CODE REVIEW

**Comment by tuomasb** [comment]
Anyone willing to take a look?

**Comment by tuomasb** [comment]
@aprofeit and @ThereExistsX would either of you have time to take a look? Sorry to bother you :)

**Comment by aprofeit** [comment]
Hi @tuomasb I'll take a look this week!

**Comment by aprofeit** [comment]
Hey @tuomasb it's been a crazy week, going to need to push this to next week.

**Comment by tuomasb** [comment]
@aprofeit OK. No problem :)

**Comment by aprofeit** [comment]
@timbeiko could I get you to review this as well? Looks pretty good to me.

**Comment by timbeiko** [comment]
LGTM. Merging it!

**Pull request closed without merging**
