### PR TITLE
Document integration helper methods.

### PR DESCRIPTION
**Pull request by lulalala**
For issue #29

### CODE REVIEW

**Comment by lulalala** [comment]
bump after three years time~
Or if you guys are not into documentation let me know and close this.

**Comment by pi3r** [comment]
I'll close this since it has been more than a year without activity

**Comment by lulalala** [comment]
@pi3r it's kinda sad because I never received any feedback from the maintainers. Even something like "we prefer to not have doc here" is better than just closing without activity (which is required from maintainers).

**Comment by pi3r** [comment]
Hey @lulalala, I've kind of done that automatically. It's not that we are not into documentation but I don't think we use it to generate html version of it anyway.

**Comment by lulalala** [comment]
@pi3r so basically a contributor should periodically bump this so there is "activity". It's kinda sad because I never received any feedback from the maintainers. Even something like "we prefer to not have doc here" is better than just closing without activity (which is required from maintainers not contributers).

The lack of documentation is making it difficult to implement the interface for a new gateway. It has nothing to do with generating HTML doc or not.

**Comment by lulalala** [comment]
@pi3r so basically a contributor should periodically bump this so there is "activity". It's kinda sad because I never received any feedback from the maintainers. Even something like "we prefer to not have doc here" is better than just closing without activity (which is required from maintainers not contributers).

The lack of documentation is making it difficult to implement the interface for a new gateway. It has nothing to do with generating HTML doc or not.

**Comment by pi3r** [comment]
To be frank this repository is not actively maintained, so I agree I was too hasty to close it. Would you want to somewhat rebase and merge it now?

**Comment by lulalala** [comment]
@pi3r I must apologize as I expressed too strongly. I didn't know this is no longer maintained. Can I find relevant discussion?

I've made the rebase. Thanks.

**Comment by pi3r** [comment]
Hey @lulalala, what I meant by "no longer maintained" is that Shopify doesn't add or update new gateway integrations.

**Pull request merged**
