### PR TITLE
Quickpay callback includes acquirer param and must be checked with md5secret from options

### PR DESCRIPTION
**Pull request by espen**

### CODE REVIEW

**Comment by koppen** [comment]
I have just verified this fix. The changes here are still relevant and correct. Would love to see this merged.

**Comment by pi3r** [comment]
I'll close this since it has been more than a year without activity

**Comment by koppen** [comment]
I get the need to close off old pull requests, but I'd venture a claim that the activity that's missing here is this PR being merged. 😉

If any other action is expected from the community before this could be merged, it would be helpful to clarify what those actions are so we can take them.

What next steps should we take in order to have these changes merged?

**Comment by pi3r** [comment]
Could you add a description on the impact of the changes and I'll get it merged.

**Comment by espen** [comment]
@pi3r this change is necessary to verify the request using the md5. The current code does not include all the attributes necessary to perform the check.

btw: This is the deprecated version of QuickPay API which now requires the use of a paid proxy. Still usable but there is a new version as added in https://github.com/activemerchant/offsite_payments/pull/205

**Pull request merged**
