### PR TITLE
Fix CI by not overriding the version requirement for the money gem

### PR DESCRIPTION
**Pull request by bdewater**
Also test against Rails 5 release versions instead of master

### CODE REVIEW

**Comment by pi3r** [comment]
:+1: lgtm, /cc @jasonwebster @Krystosterone

**Comment by bdewater** [comment]
I've been diving a bit deeper in to this issue and I think there's room for improvement. https://github.com/RubyMoney/money/pull/606 led the change that broke the Robokassa test but upon closer inspection of [OffsitePayments::Notification#amount](https://github.com/activemerchant/offsite_payments/blob/e90298b1801552070ca9cee83f649363567cb8a9/lib/offsite_payments/notification.rb#L33-L38) it seems that subclasses should also return Money objects. I think it is better to have these overrides look like the example below instead of applying a quick fix (comparing two BigDecimals) to the tests, WDYT?
```ruby
def amount
  Money.from_amount(gross, currency)
end
```

**Comment by pi3r** [comment]
I agree, can you make the change?

**Comment by bdewater** [comment]
Will do!

**Pull request merged**
