### PR TITLE
App55: Remove Gateway

### PR DESCRIPTION
**Pull request by ThereExistsX**
The App55 Gateway is dead, this PR removes App55 from Offsite Payments.

* https://www.crunchbase.com/organization/app55#/entity
* http://www.app55.com/

**Attn:**
@girasquid @aprofeit @matthelm @berkcaputcu

### CODE REVIEW

**Comment by berkcaputcu** [comment]
:fire:

**Comment by aprofeit** [comment]
What does this even do in offsite payments?

**Comment by aprofeit** [comment]
:+1:

**Comment by ThereExistsX** [comment]
@aprofeit Honestly, no idea, looks like someone may have pulled most of it out at some point in the past but forgot the fixtures.

**Pull request closed without merging**
