### PR TITLE
Add gemfile for testing on Travis

### PR DESCRIPTION
**Pull request by bdewater**
Test Shopify specific scenario. Also rename Rails 5.0 gemfile in preparation for Rails 5.1 soon.

### CODE REVIEW

**Comment by pi3r** [comment]
@bdewater Can you rebase on master? Should be green now 🤞

**Comment by elfassy** [comment]
As discussed in person, I think we should replace all `Money.new` present in this gem with `Money.from_cents` and then write a simple monkey patch
```ruby
module MoneyPatch
  def from_cents(amount, currency)
    return super if defined?(super)
    new(amount, currency)
  end
end
Money.prepend(MoneyPatch)
```

**Comment by bdewater** [comment]
What I don't like about that is we're introducing a ShopifyMoney method in a gem where RubyMoney is the assumed default. I'd turn it around like this:

```ruby
module MoneyCompatibility
  def initialize(amount, currency)
    return from_cents(amount) if defined?(from_cents)
    super
  end
end
Money.prepend(MoneyCompatibility)
```

**Comment by elfassy** [comment]
I don't think we can `return from_cents(amount)` since the initialize will likely be doing more things than just convert to cents. We'd still need to call super. How about
```ruby
module MoneyCompatibility
  def initialize(amount, currency)
    amount = from_cents(amount) if defined?(from_cents)
    super(amount, currency)
  end
end
Money.prepend(MoneyCompatibility)
```

**Pull request merged**
