### PR TITLE
MiGS Integration

### PR DESCRIPTION
**Pull request by mnoack**
This integrates MiGS (MasterCard Internet Gateway Service).

MiGS is both an offsite and onsite payment service. This PR fulfils the offsite functionality of MiGS.

I was the author of the MiGS integration in active_merchant.

### CODE REVIEW

**Comment by mnoack** [comment]
Hi @ntalbott - This code has been used for all of this year in production, getting testing every 2 weeks in our own manual testing, If there's anything I need to do to assist this PR to be merged please let me know.

**Comment by mnoack** [comment]
Bump @ntalbott If there's any changes I need to do let me know.

I also note somewhere else I think I have discussed about having non-core gateways like this one be done in "gem" form, so they don't need to be accepted by Shopify if either they don't want it or are too busy (and we're all very busy). Shopify could still manage the core gems for core payment gateways in their account (to ensure they remain compatible with api-breaking activemerchant/offsite_payments changes) although the API rarely changes.

**Comment by ntalbott** [comment]
@mnoack other than extracting it from ActiveMerchant, I don't do any maintenance of the offsite_payments library.

**Comment by mnoack** [comment]
Hi @elfassy @bdewater

I'm looking at getting some of our forked branches into master so we can take advantage of your rails 4/5 support. Can you review this PR as it seems to have gotten lost.

I'm happy to rebase all my PRs from the current master and have them testing in production before you merging, but first I would just like to know if these PR's (and the 2 that add a gateway) would be potentially mergeable (I know you won't add every gateway that is PR'd)

Also the same for my other PR's:
Code Coverage - https://github.com/activemerchant/offsite_payments/pull/189
POLiPay - https://github.com/activemerchant/offsite_payments/pull/188

**Comment by mnoack** [comment]
Hi @elfassy @bdewater - Just following up on this PR. If I'm able to assist your work (I think the code coverage PR will help there to ensure those who submit PR's are warned if they don't meet the existing testing standards for example)

**Comment by Jeff-kennedy** [comment]
Hi @mnoack We are no longer accepting new integrations through AM. Can you explain what functionality adding an offsite version of this gateway will provide, and we can see if there is an alternative solution.

**Comment by mnoack** [comment]
@Jeff-kennedy MiGS have both an onsite and offsite payment ability. This is the offsite version of what is in ActiveMerchant.

**Comment by Jeff-kennedy** [comment]
@mnoack Thanks. What we need to determine is what value adding the offsite version will add to our merchants experience. Anything you can share on why an offsite version is needed will be helpful.

**Comment by mnoack** [comment]
The case for a merchant using the offsite version over the onsite version are much the same as any other offsite version. By going offsite the merchant transfers the PCI compliance issues to the payment provider.

They also in essence ensure a well tested, reliable and perhaps due to the strong branding of the payment provider also benefit in that way.

Of course like any offsite payment they lose the ability for the customer to pay within the merchants branding and control the UX of the payment process.

MiGS offsite payment (and many other offsite payments) also benefit from reducing fraud for the merchant, because they will do 3DSecure, etc. (depending on the availability of this for the customers card, the fraud profile of the transaction/IP/etc., etc.)

**Comment by mnoack** [comment]
@Jeff-kennedy Also I note you said "AM" in your original comment. Whilst this project is Offsite Payments (which was extracted from AM). This PR is seeking to change Offsite Payments gem (and not Active Merchant gem).

Just making super-sure you're not thinking this PR is for AM (because I know what it's like to jump between a dozen projects and accidently confuse them)

Thanks

**Comment by mnoack** [comment]
@Jeff-kennedy Can you clarify that point about AM (ActiveMerchant), as per my above message. I understand why AM is quite carefully guarded, I'm just not sure if that is also the OP (Offsite Payments) approach.

There's actually a change now needed for MiGS to make it compatible (for both AM and OP), we're going to make the change to our OP fork, but in reality we're probably going to roll out own offsite_payments_migs gem which will plug into offsite_payments gem, that way we can keep up to date with latest OP code and update our gem to remain compatible where needed.

That way we don't have to keep maintaining the fork and so others (especially those in Australia) can benefit easily from our work on MiGS and POLi Pay

**Comment by seanchambo** [comment]
Definitely agree with the guy above (@mnoack)

**Comment by mnoack** [comment]
@Jeff-kennedy What was the update to my question?

As I said, and in addition the Offsite MiGS is useful to avoid PCI compliance issues (it's handled by the bank). so MiGS offline is in reality a completely separate and different solution to MiGS "onsite". I would really consider them 2 separate gateways.

**Comment by Jeff-kennedy** [comment]
@mnoack apologies for the delay. We are no longer accepting new integrations into Shopify through this method (Direct or offsite through Active merchant).

**Pull request closed without merging**
