### PR TITLE
Update PayFast integration.

### PR DESCRIPTION
**Pull request by nashby**

### CODE REVIEW

**Comment by nashby** [comment]
@andrewpaliga sorry, but I don't really understand the problem. You, as a shop owner, have to put item_name field to the form since it's a mandatory field. Why do you say it will never be sent?

**Comment by andrewpaliga** [comment]
Hi @nashby sorry for the delay on this. Can you try mapping only the parameters [here](https://github.com/Shopify/offsite_payments/blob/master/lib/offsite_payments/integrations/universal.rb#L88) ?

The `:item_name` will not be available there.

Alternatively you can use the universal implementation (which is working and merged) for you integration. You can find and example app and documentation [here](https://github.com/Shopify/offsite-gateway-sim)

This is the fastest/easiest way to integrate with Shopify.

**Comment by nashby** [comment]
Hey @andrewdunbar, don't worry, it's ok!

If I remove item_name from the mapping is it possible for users to use it somehow? I mean it's a mandatory field for PayFast.

**Comment by andrewpaliga** [comment]
@nashby you can leave `item_name` in just understand that Shopify will never pass this field. Your code must not break in this case. Currently your code breaks if `:item_name` is nil.

**Comment by nashby** [comment]
@andrewpaliga hey, it's been awhile. :)

Can you please take a look again? I believe I fixed it now. Thanks!

**Comment by pi3r** [comment]
I'll close this since it has been more than a year without activity

**Pull request closed without merging**
