### PR TITLE
Update paydollar.rb

### PR DESCRIPTION
**Pull request by SimonLeungAPHK**
As our system structure have some update, the payment link require to change.

### CODE REVIEW

**Comment by elfassy** [comment]
@SimonLeungAPHK looks good, can you please update the tests too, thanks

**Comment by SimonLeungAPHK** [comment]
@elfassy The test page have updated, please check again. Thanks.

**Comment by SimonLeungAPHK** [comment]
@elfassy May I know when will changes apply to production? Thanks.

**Comment by elfassy** [comment]
@SimonLeungAPHK Looks like tests are not passing. It usually takes a couple of weeks once merged to get changes to production

**Comment by SimonLeungAPHK** [comment]
@elfassy We have applied the changes again after the test run failed.  How would we rerun the test again? Or we have to submit another pull request ? thanks.

**Comment by elfassy** [comment]
test will run after any code change to this PR

**Comment by elfassy** [comment]
```
<"https://www.paydollar.com/b2c2/eng/payment/payForm.jsp"> expected but was
<"https://www.paydollar.com/b2c2/eng/payment/payShopify.jsp">
```
You also need to update the tests:
https://github.com/activemerchant/offsite_payments/blob/master/test/unit/integrations/paydollar/paydollar_module_test.rb#L16
https://github.com/activemerchant/offsite_payments/blob/master/test/unit/integrations/paydollar/paydollar_module_test.rb#L23

**Comment by SimonLeungAPHK** [comment]
@elfassy We have updated the test. Could you help to continue process this PR?

**Pull request merged**
